version: '3.8'
services:
  redis:
    image: redis:7.0.8-alpine
    container_name: newzet-redis
    environment:
      - SPRING_REDIS_PASSWORD=${SPRING_REDIS_PASSWORD}
    command: [
      'redis-server',
      '--requirepass', '${SPRING_REDIS_PASSWORD}',
      '--bind', '0.0.0.0',
      '--maxmemory', '512mb',
      '--maxmemory-policy', 'volatile-lru',
      '--appendonly', 'yes',
      '--appendfsync', 'everysec',
      '--aof-use-rdb-preamble', 'yes',
      '--auto-aof-rewrite-percentage', '100',
      '--auto-aof-rewrite-min-size', '64mb'
    ]
    ports:
      - '16379:6379'
    restart: unless-stopped
    networks:
      - newzet-network
    deploy:
      resources:
        limits:
          memory: 600m
    healthcheck:
      test: [ 'CMD', 'redis-cli', '-a', '${SPRING_REDIS_PASSWORD}', 'ping' ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - redis-data:/var/lib/redis

volumes:
  redis-data:
networks:
  newzet-network:
    driver: bridge
