spring:
  lifecycle:
    timeout-per-shutdown: 60s
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost:5432}/${DB_NAME:newzet_db}?prepareThreshold=0
    username: ${DB_USERNAME:newzet}
    password: ${DB_PASSWORD:newzet}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      idle-timeout: 30000  # 30초 후 유휴 커넥션 닫기
      max-lifetime: 1800000  # 30분 후 커넥션 강제 갱신
      connection-timeout: 30000  # 30초 동안 커넥션을 얻지 못하면 에러 발생

  jpa:
    hibernate:
      ddl-auto: none
      jdbc:
        time-zone: Asia/Seoul
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.jdbc.batch_size: 100
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.generate_statistics: false #Hibernate에서 성능 통계 정보 생성 여부 (배치처리 확인용)
    show-sql: ${SPRING_JPA_SHOW_SQL:true}

  data:
    redis:
      host: ${SPRING_REDIS_HOST:127.0.0.1}
      port: ${SPRING_REDIS_PORT:16379}
      password: ${SPRING_REDIS_PASSWORD:newzet}

jwt:
  secret:
    ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
info:
  app:
    version: ${APP_VERSION:latest}

server:
  shutdown: graceful
  tomcat:
    mbeanregistry:
      enabled: true
