spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      idle-timeout: 30000  # 30초 후 유휴 커넥션 닫기
      max-lifetime: 1800000  # 30분 후 커넥션 강제 갱신
      connection-timeout: 30000  # 30초 동안 커넥션을 얻지 못하면 에러 발생

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_DDL}
      jdbc:
        time-zon: Asia/Seoul
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: ${SPRING_JPA_SHOW_SQL}

  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}
      password: ${SPRING_REDIS_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
info:
  app:
    version: ${APP_VERSION}
