FROM postgres:15.6

COPY ./init/db /docker-entrypoint-initdb.d/init-db

COPY ./init/init.sh /docker-entrypoint-initdb.d/01-init.sh
COPY ./init/seeding.sh /docker-entrypoint-initdb.d/02-seeding.sh

ENV POSTGRES_PASSWORD=newzet
ENV POSTGRES_USER=newzet
ENV POSTGRES_DB=newzet_db
ENV TZ=Asia/Seoul
