name: CI Pipeline

on:
  pull_request:
    branches:
      - dev
    types:
      - opened
      - synchronize

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      should-run-ci: ${{ steps.check.outputs.run_ci }}
    steps:
      - uses: actions/checkout@v4

      - id: check
        run: |
          git fetch origin ${{ github.base_ref }}
          if ! git diff --name-only origin/${{ github.base_ref }}...HEAD \
            | grep -v -E '^(README\.md|\.gitignore)$' \
            | grep .; then
            echo "run_ci=false" >> $GITHUB_OUTPUT
          else
            echo "run_ci=true" >> $GITHUB_OUTPUT
          fi

  ci:
    needs: check-changes
    if: needs.check-changes.outputs.should-run-ci == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: get repository code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-write-only: true

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: build code and test
        run: ./gradlew clean build
