name: Java CI with Gradle

on:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'src/**'
    types:
      - opened
      - synchronize

jobs:
  build-and-test:
    if: github.event.action == 'opened' || github.event.action == 'synchronize'
    runs-on: ubuntu-latest

    steps:
      - name: Check platform
        run: uname -m

      - name: get repository code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: build code and test
        run: ./gradlew clean build
