name: Java CI with Gradle

on:
  push:
    branches:
      - dev
    paths:
      - 'src/**'
  pull_request:
    branches:
      - main
      - dev
    types:
      - opened
      - synchronize
#      - closed

jobs:
  build-and-test:
    #    if: github.event.action == 'opened' || github.event.action == 'synchronize'
    runs-on: ubuntu-latest

    steps:
      - name: Check platform
        run: uname -m

      - name: get repository code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Inject application.yml
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.TEST_APPLICATION_YML }}" > src/main/resources/application.yml
          echo "${{ secrets.TEST_DOCKER_COMPOSE_YML }}" > docker-compose.yml

      - name: Validate YAML
        run: |
          yamllint docker-compose.yml

      - name: Set file permissions
        run: |
          chmod 644 docker-compose.yml

      - name: Verify file content
        run: |
          echo "=== docker-compose.yml content ==="
          cat docker-compose.yml
          echo "================================="

      - name: Build and Test with Gradle
        run: |
          docker compose -f docker-compose.yml up -d
          ./gradlew clean build
          docker compose -f docker-compose.yml down
