name: Java CI with Gradle

on:
  push:
    branches:
      - dev
    paths:
      - 'src/**'
  pull_request:
    branches:
      - main
      - dev
    types:
      - opened
      - synchronize
#      - closed

jobs:
  build-and-test:
    #    if: github.event.action == 'opened' || github.event.action == 'synchronize'
    runs-on: ubuntu-latest

    steps:
      - name: Check platform
        run: uname -m

      - name: get repository code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Inject application.yml
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.TEST_APPLICATION_YML }}" | base64 -d | sed 's/\r$//' > src/main/resources/application.yml
          echo "${{ secrets.TEST_DOCKER_COMPOSE_YML }}" | base64 -d | sed 's/\r$//' > docker-compose.yml

      - name: Start Container
        run: docker compose -f docker-compose.yml up -d

      - name: Wait for database
        run: |
          while ! docker exec newzet-test-postgres pg_isready; do
            sleep 1
          done
        timeout-minutes: 1

      - name: Check container status
        run: docker ps

      - name: Test database connection
        run: docker exec newzet-test-postgres psql -U test_user -d test_db -c "\l"

      - name: build code and test
        run: ./gradlew clean build

      - name: Quit Container
        run: docker compose -f docker-compose.yml down
